import { readFileSync } from "fs";
import { resolve } from "path";

export async function codegenWithClaude({ planText, repoSummary, model, apiKey }) {
    // 这里给出“最小可用”的伪实现：直接返回若干文件草案。
    // 你接 Anthropic API 时，把下面改为 fetch('https://api.anthropic.com/v1/messages', ...) 即可。
    // 返回格式：[{ path, content, rationale }]
    const targets = extractFilesFromPlan(planText);
    const content = `// generated by Claude (demo)
// 根据 plan 生成的占位代码：请替换成真实 API 调用结果
`;
    return targets.map(p => ({ path: p, content, rationale: "demo content" }));
}

function extractFilesFromPlan(planText) {
    return (planText.match(/^\s*-\s+(.+?)\s*$/gmi) || [])
        .map(l => l.replace(/^\s*-\s+/, "").trim()).filter(Boolean);
}