export const anthropicAdapter = {
    async invoke(role, payload, { step }) {
        const apiKey = process.env[step.apiKeyEnv || ""];
        if (!apiKey) throw new Error("缺少 ANTHROPIC_API_KEY");
        // TODO: 真正的 API 请求；这里先返回 demo
        if (role === "codegen") {
            const files = extractTargets(payload.planText).map(p => ({
                path: p,
                content: demoScaffold(p, payload),
                rationale: "demo content from Claude adapter"
            }));
            return { ok: true, files };
        }
        if (role === "review") {
            return { ok: true, summary: "（Claude demo）未发现高风险", risks: [], suggestions: [] };
        }
        if (role === "second_opinion") {
            return { ok: true, verdict: "ok", notes: "（Claude demo）同意整体方案" };
        }
        return { ok: false };
    }
};

function extractTargets(planText = "") {
    return (planText.match(/^\s*-\s+(.+?)\s*$/gmi) || [])
        .map(l => l.replace(/^\s*-\s+/, "").trim()).filter(Boolean);
}
function demoScaffold(pathRel, payload) {
    return `// generated by Claude demo\n// file: ${pathRel}\n// plan: ${(payload.planText || "").slice(0, 200)}\n`;
}