// DeepSeek adapter - OpenAI-style chat completions
const DEFAULT_BASE_URL = "https://api.deepseek.com/chat/completions";

async function callDeepseekChat({ apiKey, model, messages, extra }) {
    if (!apiKey) {
        throw new Error("缺少 DEEPSEEK_API_KEY（或配置的 api_key_env 环境变量）");
    }

    const body = {
        model: model || "deepseek-chat",
        messages,
        // 默认参数可以由 models.conf 中 future 字段扩展，这里先给出一组保守默认值
        temperature: 1,
        top_p: 1,
        max_tokens: 4096,
        stream: false,
        response_format: { type: "text" },
        ...extra
    };

    const res = await fetch(process.env.DEEPSEEK_BASE_URL || DEFAULT_BASE_URL, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
            Authorization: `Bearer ${apiKey}`
        },
        body: JSON.stringify(body)
    });

    if (!res.ok) {
        const txt = await res.text().catch(() => "");
        throw new Error(`DeepSeek HTTP ${res.status}: ${txt.slice(0, 400)}`);
    }

    const data = await res.json();
    const choice = (data.choices && data.choices[0]) || {};
    const message = choice.message || {};
    const content = typeof message.content === "string" ? message.content : "";

    return { data, content };
}

export const deepseekAdapter = {
    async invoke(role, payload, { step }) {
        const apiKeyEnv = step.apiKeyEnv || step.api_key_env || "DEEPSEEK_API_KEY";
        const apiKey = process.env[apiKeyEnv];
        const model = step.model || "deepseek-chat";

        // 根据角色构造不同的系统提示和用户内容
        if (role === "review") {
            const diff = payload.diffText || "";
            const systemMsg = {
                role: "system",
                content: "你是一个资深代码审查助手，请阅读 diff 并给出风险与建议。"
            };
            const userMsg = {
                role: "user",
                content: `下面是代码 diff，请用简要条目说明：1）总体评价；2）潜在风险；3）改进建议。\n\n${diff.slice(0, 60000)}`
            };
            const { content } = await callDeepseekChat({
                apiKey,
                model,
                messages: [systemMsg, userMsg],
                extra: {}
            });
            return {
                ok: true,
                summary: content || "（DeepSeek）代码审查结果",
                risks: [],
                suggestions: []
            };
        }

        if (role === "second_opinion") {
            const plan = payload.planText || "";
            const diff = payload.diffText || "";
            const systemMsg = {
                role: "system",
                content: "你是一个第二视角审查者，请从整体方案和 diff 的角度给出审查意见。"
            };
            const userMsg = {
                role: "user",
                content: `下面是计划与 diff，请给出高层次的第二意见（可以用要点列出）：\n\n[PLAN]\n${plan.slice(0, 2000)}\n\n[DIFF]\n${diff.slice(0, 60000)}`
            };
            const { content } = await callDeepseekChat({
                apiKey,
                model,
                messages: [systemMsg, userMsg],
                extra: {}
            });
            return {
                ok: true,
                verdict: "ok",
                notes: content || "（DeepSeek）第二意见"
            };
        }

        if (role === "codegen") {
            // 这里先实现一个最小可用版本：根据 plan 生成文件说明/占位内容。
            const plan = payload.planText || "";
            const filesFromPayload = Array.isArray(payload.files) ? payload.files : [];
            const targets = filesFromPayload.length
                ? filesFromPayload
                : extractTargets(plan);

            const systemMsg = {
                role: "system",
                content: "你是代码生成助手，请根据规划为每个目标文件生成示例代码。"
            };
            const userMsg = {
                role: "user",
                content: `根据下面的计划，为这些文件生成合理的示例实现（每个文件一段代码即可）：\n\n目标文件：\n${targets.map((f) => `- ${f}`).join("\n")}\n\n[PLAN]\n${plan.slice(0, 4000)}`
            };

            const { content } = await callDeepseekChat({
                apiKey,
                model,
                messages: [systemMsg, userMsg],
                extra: {}
            });

            // 目前先将返回内容整体作为所有文件的占位内容，后续可根据约定格式解析出每个文件的具体实现。
            const files = targets.map((p) => ({
                path: p,
                content: `// generated by DeepSeek\n// file: ${p}\n\n${content || ""}`,
                rationale: "generated by deepseekAdapter (demo)"
            }));

            return { ok: true, files };
        }

        return { ok: false };
    }
};

function extractTargets(planText = "") {
    return (planText.match(/^\s*-\s+(.+?)\s*$/gim) || [])
        .map((l) => l.replace(/^\s*-\s+/, "").trim())
        .filter(Boolean);
}

