import fs from "fs-extra";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import { execa } from "execa";
import chalk from "chalk";

export async function runPlanningWithInputs({ cwd, aiDir, tasksDir, taskId, metaPath, inputs }) {
    const logsDir = resolve(tasksDir, taskId, "logs", "openspec");
    fs.ensureDirSync(logsDir);

    const { title, why, what, req, targets, risks, accept } = inputs;
    const changeId = `task-${taskId}`;
    const openspecRoot = aiDir;
    const changeDir = resolve(openspecRoot, "openspec", "changes", changeId);
    fs.ensureDirSync(changeDir);

    const titleText = title || `Task ${taskId}`;
    const changeMd = [
        "---",
        `id: ${changeId}`,
        `title: ${titleText}`,
        "owner: @you",
        "risk: medium",
        "---",
        "",
        "## Why",
        (why || "(待补充)"),
        "",
        "## What Changes",
        (what || "(待补充)"),
        "",
        "## Requirements",
        (req ? req.split(/[,，]/).map(s => s.trim()).filter(Boolean).map(s => `- ${s}`).join("\n") || "- (待补充)" : "- (待补充)"),
        "",
        "## Targets",
        (targets ? targets.split(/[,，]/).map(s => s.trim()).filter(Boolean).map(s => `- ${s}`).join("\n") || "- (待补充)" : "- (待补充)"),
        "",
        "## Risks and Mitigations",
        (risks || "(待补充)"),
        "",
        "## Acceptance",
        (accept ? accept.split(/[,，]/).map(s => s.trim()).filter(Boolean).map(s => `- ${s}`).join("\n") || "- (待补充)" : "- (待补充)"),
        ""
    ].join("\n");
    writeFileSync(resolve(changeDir, "change.md"), changeMd, "utf-8");

    const proposalPath = resolve(changeDir, "proposal.md");
    if (!existsSync(proposalPath)) {
        const proposal = [
            `# Proposal for ${changeId}`,
            "",
            "This proposal was generated by AI Tools Chain.",
            "See change.md for detailed Why/What/Requirements/Targets/Risks/Acceptance.",
            ""
        ].join("\n");
        writeFileSync(proposalPath, proposal, "utf-8");
    }

    const specsDir = resolve(changeDir, "specs", "task");
    fs.ensureDirSync(specsDir);
    const reqList = (req || "").split(/[,，]/).map(s => s.trim()).filter(Boolean);
    const primaryReq = reqList[0] || titleText || `Task ${taskId}`;
    const specMd = [
        "## ADDED Requirements",
        "",
        `### Requirement: ${primaryReq}`,
        "",
        `The system SHALL: ${primaryReq || "satisfy this autogenerated requirement."}`,
        "",
        "#### Scenario: basic usage",
        "- This scenario was generated by AI Tools Chain.",
        "- See change.md for full context and details.",
        ""
    ].join("\n");
    writeFileSync(resolve(specsDir, "spec.md"), specMd, "utf-8");

    const tasksPath = resolve(changeDir, "tasks.md");
    if (!existsSync(tasksPath)) {
        const tasksMd = [
            "# Tasks",
            "",
            "1. Implement the changes described in change.md.",
            "2. Add or update tests to cover requirements and scenarios.",
            "3. Run the evaluation pipeline and ensure it passes.",
            ""
        ].join("\n");
        writeFileSync(tasksPath, tasksMd, "utf-8");
    }

    try {
        const { stdout: vout, stderr: verr } = await execa("openspec", ["validate", "--changes", "--json", "--no-interactive"], { cwd: openspecRoot });
        writeFileSync(resolve(logsDir, "validate.json"), vout || "{}", "utf-8");
        if (verr) writeFileSync(resolve(logsDir, "validate.log"), verr, "utf-8");
    } catch (e) {
        const msg = e?.stdout || e?.stderr || e?.message || String(e);
        writeFileSync(resolve(logsDir, "validate.error.log"), String(msg), "utf-8");
        console.log(chalk.red("openspec validate 失败："), chalk.gray(String(msg).slice(0, 400)));
    }

    try {
        const { stdout } = await execa("openspec", ["show", "--type", "change", changeId], { cwd: openspecRoot });
        const planFile = resolve(tasksDir, taskId, "plan.md");
        writeFileSync(planFile, stdout || "", "utf-8");
        writeFileSync(resolve(logsDir, "show.md.log"), stdout || "", "utf-8");
    } catch (e) {
        const msg = e?.stdout || e?.stderr || e?.message || String(e);
        writeFileSync(resolve(logsDir, "show-md.error.log"), String(msg), "utf-8");
        console.log(chalk.red("openspec show (markdown) 失败："), chalk.gray(String(msg).slice(0, 400)));
    }

    try {
        const { stdout } = await execa("openspec", ["show", "--json", "--type", "change", changeId], { cwd: openspecRoot });
        const jsonPath = resolve(tasksDir, taskId, "plan.openspec.json");
        writeFileSync(jsonPath, stdout || "{}", "utf-8");
        writeFileSync(resolve(logsDir, "show.json.log"), stdout || "", "utf-8");
    } catch (e) {
        const msg = e?.stdout || e?.stderr || e?.message || String(e);
        writeFileSync(resolve(logsDir, "show-json.error.log"), String(msg), "utf-8");
    }

    const meta = JSON.parse(readFileSync(metaPath, "utf-8"));
    meta.status = "plan";
    writeFileSync(metaPath, JSON.stringify(meta, null, 2));
}

