import { callDeepseekChat, loadProjectPrompt, extractTargets, extractJson } from "./common.mjs";

export async function handleCodegen({ apiKey, model, aiDir, payload }) {
    const plan = payload.planText || "";
    const filesFromPayload = Array.isArray(payload.files) ? payload.files : [];
    const targets = filesFromPayload.length ? filesFromPayload : extractTargets(plan);
    if (!targets.length) {
        return {
            ok: false,
            error: "未从计划中解析到目标文件；请在规划中增加文件列表，或在 plan.files.json 中显式指定。"
        };
    }

    const systemContent = loadProjectPrompt(
        aiDir,
        "codegen",
        ""
    );
    const systemMsg = {
        role: "system",
        content: systemContent
    };
    const userMsg = {
        role: "user",
        content: [
            "根据下面的规划，为这些目标文件生成对应的实现：",
            "",
            "目标文件列表：",
            targets.map((f) => `- ${f}`).join("\n"),
            "",
            "[PLAN]",
            plan.slice(0, 4000)
        ].join("\n")
    };

    const { content } = await callDeepseekChat({
        apiKey,
        model,
        messages: [systemMsg, userMsg],
        extra: {}
    });
    try {
        const text = extractJson(content || "");
        const parsed = JSON.parse(text);
        const jsonFiles = Array.isArray(parsed.files) ? parsed.files : [];

        if (!jsonFiles.length) {
            return {
                ok: false,
                error: "codegen_json_missing_files_array"
            };
        }

        const files = jsonFiles
            .filter((f) => f && typeof f.path === "string" && typeof f.content === "string")
            .map((f) => ({
                path: f.path,
                content: f.content,
                rationale: f.rationale || "generated by deepseekAdapter",
                intent: f.intent || ""
            }));

        if (!files.length) {
            return {
                ok: false,
                error: "codegen_json_no_valid_file_entries"
            };
        }

        return { ok: true, files };
    } catch {
        return {
            ok: false,
            error: "codegen_json_parse_failed"
        };
    }
}
